/* Nerchuko — Telugu curriculum data
   146 cards across 16 weekly themes (4 months). Add more cards any time by
   appending to a week's `cards` array — nothing else needs to change. */

const WEEKS_TE = [
  { month: 1, week: 1, theme: "Greetings & Politeness", cards: [
    { en: "Hello / Greetings", te: "నమస్కారం", tr: "namaskaram" },
    { en: "How are you? (formal)", te: "మీరు ఎలా ఉన్నారు?", tr: "meeru elaa unnaaru?" },
    { en: "I am fine", te: "నేను బాగున్నాను", tr: "nenu baagunnaanu" },
    { en: "Thank you", te: "ధన్యవాదాలు", tr: "dhanyavaadaalu" },
    { en: "Please", te: "దయచేసి", tr: "dayachesi" },
    { en: "Sorry / Excuse me", te: "క్షమించండి", tr: "kshaminchandi" },
    { en: "Yes", te: "అవును", tr: "avunu" },
    { en: "No", te: "కాదు", tr: "kaadu" },
    { en: "What is your name?", te: "మీ పేరు ఏమిటి?", tr: "mee peru emiti?" },
    { en: "My name is ___", te: "నా పేరు ___", tr: "naa peru ___" },
    { en: "Good morning", te: "శుభోదయం", tr: "shubhodayam" },
    { en: "Goodbye (casual)", te: "వెళ్తాను", tr: "veltaanu", note: "Literally \"I'll go\" — the everyday casual way to say bye." },
  ]},
  { month: 1, week: 2, theme: "Pronouns & Basics", cards: [
    { en: "I", te: "నేను", tr: "nenu" },
    { en: "You (respectful)", te: "మీరు", tr: "meeru", note: "Use with elders, strangers, colleagues." },
    { en: "You (casual)", te: "నువ్వు", tr: "nuvvu", note: "Only for close friends, kids, or people younger than you." },
    { en: "He", te: "అతను", tr: "atanu" },
    { en: "She", te: "ఆమె", tr: "aame" },
    { en: "We", te: "మేము", tr: "memu" },
    { en: "They", te: "వాళ్ళు", tr: "vaallu" },
    { en: "This", te: "ఇది", tr: "idi" },
    { en: "That", te: "అది", tr: "adi" },
    { en: "Where", te: "ఎక్కడ", tr: "ekkada" },
    { en: "What is this?", te: "ఇది ఏమిటి?", tr: "idi emiti?" },
    { en: "I am an engineer", te: "నేను ఇంజనీర్ ని", tr: "nenu engineer ni", note: "Pattern: nenu [role] ni = \"I am a/an ___\"" },
  ]},
  { month: 1, week: 3, theme: "Numbers & Time", cards: [
    { en: "One", te: "ఒకటి", tr: "okati" },
    { en: "Two", te: "రెండు", tr: "rendu" },
    { en: "Three", te: "మూడు", tr: "moodu" },
    { en: "Four", te: "నాలుగు", tr: "naalugu" },
    { en: "Five", te: "అయిదు", tr: "aidu" },
    { en: "Six", te: "ఆరు", tr: "aaru" },
    { en: "Seven", te: "ఏడు", tr: "edu" },
    { en: "Eight", te: "ఎనిమిది", tr: "enimidi" },
    { en: "Nine", te: "తొమ్మిది", tr: "tommidi" },
    { en: "Ten", te: "పది", tr: "padi" },
    { en: "Today", te: "ఈరోజు", tr: "eeroju" },
    { en: "Tomorrow", te: "రేపు", tr: "repu" },
    { en: "Yesterday", te: "నిన్న", tr: "ninna" },
    { en: "What's the time?", te: "సమయం ఎంత?", tr: "samayam enta?" },
  ]},
  { month: 1, week: 4, theme: "Family & People", cards: [
    { en: "Mother", te: "అమ్మ", tr: "amma" },
    { en: "Father", te: "నాన్న", tr: "nanna" },
    { en: "Elder brother", te: "అన్న", tr: "anna" },
    { en: "Elder sister", te: "అక్క", tr: "akka" },
    { en: "Friend (male)", te: "స్నేహితుడు", tr: "snehithudu" },
    { en: "Friend (female)", te: "స్నేహితురాలు", tr: "snehithuraalu" },
    { en: "Children", te: "పిల్లలు", tr: "pillalu" },
    { en: "This is my friend", te: "ఇది నా స్నేహితుడు", tr: "idi naa snehithudu" },
  ]},
  { month: 2, week: 5, theme: "Everyday Verbs", cards: [
    { en: "I want tea", te: "నాకు టీ కావాలి", tr: "naaku tea kaavaali", note: "Pattern: naaku ___ kaavaali = \"I want ___\"" },
    { en: "I like it", te: "నాకు ఇష్టం", tr: "naaku ishtam" },
    { en: "I don't like it", te: "నాకు ఇష్టం లేదు", tr: "naaku ishtam ledu" },
    { en: "I understand", te: "నాకు అర్థమైంది", tr: "naaku arthamaindi" },
    { en: "I don't understand", te: "నాకు అర్థం కాలేదు", tr: "naaku artham kaaledu" },
    { en: "I know", te: "నాకు తెలుసు", tr: "naaku telusu" },
    { en: "I don't know", te: "నాకు తెలియదు", tr: "naaku teliyadu" },
    { en: "I am going", te: "నేను వెళ్తున్నాను", tr: "nenu veltunnaanu" },
    { en: "I am coming", te: "నేను వస్తున్నాను", tr: "nenu vastunnaanu" },
    { en: "I am eating", te: "నేను తింటున్నాను", tr: "nenu tintunnaanu" },
    { en: "Give me water", te: "నాకు నీళ్ళు ఇవ్వండి", tr: "naaku neellu ivvandi" },
    { en: "Help me", te: "నాకు సహాయం చేయండి", tr: "naaku sahaayam cheyandi" },
  ]},
  { month: 2, week: 6, theme: "Asking Questions", cards: [
    { en: "What", te: "ఏమిటి", tr: "emiti" },
    { en: "Who", te: "ఎవరు", tr: "evaru" },
    { en: "When", te: "ఎప్పుడు", tr: "eppudu" },
    { en: "Why", te: "ఎందుకు", tr: "enduku" },
    { en: "How", te: "ఎలా", tr: "elaa" },
    { en: "How much / many", te: "ఎంత", tr: "enta" },
    { en: "Which", te: "ఏది", tr: "edi" },
    { en: "Can I get water?", te: "నాకు నీళ్ళు దొరుకుతుందా?", tr: "naaku neellu dorukutundaa?" },
    { en: "How much is this?", te: "ఇది ఎంత?", tr: "idi enta?" },
    { en: "Is it available?", te: "ఉందా?", tr: "undaa?" },
  ]},
  { month: 2, week: 7, theme: "Food & Dining", cards: [
    { en: "Water", te: "నీళ్ళు", tr: "neellu" },
    { en: "Rice / food", te: "అన్నం", tr: "annam" },
    { en: "Meal", te: "భోజనం", tr: "bhojanam" },
    { en: "Tasty / good", te: "బాగుంది", tr: "baagundi" },
    { en: "Spicy", te: "కారం", tr: "kaaram" },
    { en: "Sweet", te: "తీపి", tr: "teepi" },
    { en: "I am hungry", te: "నాకు ఆకలిగా ఉంది", tr: "naaku aakaligaa undi" },
    { en: "I am thirsty", te: "నాకు దాహంగా ఉంది", tr: "naaku daahamgaa undi" },
    { en: "Coffee please", te: "కాఫీ ఇవ్వండి", tr: "coffee ivvandi" },
    { en: "Do you have tea?", te: "మీ దగ్గర టీ ఉందా?", tr: "mee daggara tea undaa?" },
    { en: "Bill please", te: "బిల్లు ఇవ్వండి", tr: "billu ivvandi" },
  ]},
  { month: 2, week: 8, theme: "Shopping & Directions", cards: [
    { en: "Shop", te: "దుకాణం", tr: "dukaanam" },
    { en: "Money", te: "డబ్బులు", tr: "dabbulu" },
    { en: "Expensive", te: "ఖరీదైనది", tr: "khareedainadi" },
    { en: "Cheap", te: "చవక", tr: "chavaka" },
    { en: "Left", te: "ఎడమ", tr: "edama" },
    { en: "Right", te: "కుడి", tr: "kudi" },
    { en: "Straight", te: "నేరుగా", tr: "nerugaa" },
    { en: "Near", te: "దగ్గర", tr: "daggara" },
    { en: "Far", te: "దూరం", tr: "dooram" },
    { en: "Where is the bathroom?", te: "బాత్రూమ్ ఎక్కడ ఉంది?", tr: "bathroom ekkada undi?" },
    { en: "Stop here", te: "ఇక్కడ ఆపండి", tr: "ikkada aapandi", note: "Useful in an auto or cab." },
  ]},
  { month: 3, week: 9, theme: "Talking About the Past", cards: [
    { en: "I went", te: "నేను వెళ్ళాను", tr: "nenu vellaanu" },
    { en: "I came", te: "నేను వచ్చాను", tr: "nenu vacchaanu" },
    { en: "I ate", te: "నేను తిన్నాను", tr: "nenu tinnaanu" },
    { en: "I did (it)", te: "నేను చేశాను", tr: "nenu chesaanu" },
    { en: "I saw", te: "నేను చూశాను", tr: "nenu choosaanu" },
    { en: "I said", te: "నేను చెప్పాను", tr: "nenu cheppaanu" },
    { en: "Did you eat?", te: "మీరు తిన్నారా?", tr: "meeru tinnaaraa?" },
    { en: "I finished it", te: "నేను పూర్తి చేశాను", tr: "nenu poorthi chesaanu" },
  ]},
  { month: 3, week: 10, theme: "Talking About the Future", cards: [
    { en: "I will go", te: "నేను వెళ్తాను", tr: "nenu veltaanu" },
    { en: "I will come", te: "నేను వస్తాను", tr: "nenu vastaanu" },
    { en: "I will do it", te: "నేను చేస్తాను", tr: "nenu chestaanu" },
    { en: "I will call you", te: "నేను మీకు కాల్ చేస్తాను", tr: "nenu meeku call chestaanu" },
    { en: "Will you come?", te: "మీరు వస్తారా?", tr: "meeru vastaaraa?" },
    { en: "See you tomorrow", te: "రేపు కలుద్దాం", tr: "repu kaluddaam" },
  ]},
  { month: 3, week: 11, theme: "Feelings & States", cards: [
    { en: "Happiness", te: "సంతోషం", tr: "santosham" },
    { en: "Sadness", te: "బాధ", tr: "baadha" },
    { en: "I am tired", te: "నాకు అలసటగా ఉంది", tr: "naaku alasatagaa undi" },
    { en: "I am angry", te: "నాకు కోపంగా ఉంది", tr: "naaku kopamgaa undi" },
    { en: "I am not feeling well", te: "నాకు ఒంట్లో బాగోలేదు", tr: "naaku ontlo baagoledu" },
    { en: "I am scared", te: "నాకు భయంగా ఉంది", tr: "naaku bhayamgaa undi" },
    { en: "I love you", te: "నేను నిన్ను ప్రేమిస్తున్నాను", tr: "nenu ninnu premistunnaanu" },
    { en: "I'm so happy", te: "నాకు చాలా సంతోషంగా ఉంది", tr: "naaku chaalaa santoshamgaa undi" },
  ]},
  { month: 3, week: 12, theme: "Connecting Words", cards: [
    { en: "And / also", te: "ఇంకా", tr: "inkaa" },
    { en: "But", te: "కానీ", tr: "kaanee" },
    { en: "Because", te: "ఎందుకంటే", tr: "endukante" },
    { en: "If", te: "ఒకవేళ", tr: "okavela" },
    { en: "Also / too", te: "కూడా", tr: "koodaa" },
    { en: "Okay / alright", te: "సరే", tr: "sare" },
    { en: "Really?", te: "నిజంగానా?", tr: "nijamgaanaa?" },
    { en: "Wait", te: "ఆగండి", tr: "aagandi" },
    { en: "Come here", te: "ఇక్కడికి రండి", tr: "ikkadiki randi" },
    { en: "Listen", te: "వినండి", tr: "vinandi" },
  ]},
  { month: 4, week: 13, theme: "At a Shop", cards: [
    { en: "Do you have this?", te: "మీ దగ్గర ఇది ఉందా?", tr: "mee daggara idi undaa?" },
    { en: "I need an auto", te: "నాకు ఆటో కావాలి", tr: "naaku auto kaavaali" },
    { en: "Please reduce the price", te: "రేటు తగ్గించండి", tr: "rate tagginchandi" },
    { en: "I'll take this", te: "ఇది తీసుకుంటాను", tr: "idi teesukuntaanu" },
    { en: "No need", te: "వద్దు", tr: "vaddu", note: "Very common word — the polite way to decline anything." },
    { en: "Enough / that's it", te: "చాలు", tr: "chaalu" },
  ]},
  { month: 4, week: 14, theme: "Meeting People", cards: [
    { en: "Where are you from?", te: "మీరు ఎక్కడ నుంచి?", tr: "meeru ekkada nunchi?" },
    { en: "I am from Bengaluru", te: "నేను బెంగళూరు నుంచి", tr: "nenu Bengaluru nunchi" },
    { en: "What do you do?", te: "మీరు ఏం చేస్తుంటారు?", tr: "meeru em chestuntaaru?" },
    { en: "I work at Bosch", te: "నేను బాష్ కంపెనీలో పని చేస్తాను", tr: "nenu Bosch company-lo pani chestaanu" },
    { en: "Nice to meet you", te: "మిమ్మల్ని కలవడం సంతోషంగా ఉంది", tr: "mimmalni kalavadam santoshamgaa undi" },
    { en: "How old are you?", te: "మీ వయసు ఎంత?", tr: "mee vayasu enta?" },
  ]},
  { month: 4, week: 15, theme: "Travel & Transport", cards: [
    { en: "Bus stop", te: "బస్ స్టాప్", tr: "bus stop" },
    { en: "Auto rickshaw", te: "ఆటో", tr: "auto" },
    { en: "Turn left", te: "ఎడమవైపు తిరగండి", tr: "edamavaipu tiragandi" },
    { en: "Turn right", te: "కుడివైపు తిరగండి", tr: "kudivaipu tiragandi" },
    { en: "How far is it?", te: "ఎంత దూరం?", tr: "enta dooram?" },
    { en: "Take me to the airport", te: "నన్ను ఎయిర్‌పోర్ట్‌కి తీసుకెళ్ళండి", tr: "nannu airport-ki teesukellandi" },
  ]},
  { month: 4, week: 16, theme: "Everyday Fillers & Review", cards: [
    { en: "Sure / okay then", te: "అలాగే", tr: "alaage" },
    { en: "Anything else?", te: "ఇంకేమైనా?", tr: "inkemainaa?" },
    { en: "No problem / it's okay", te: "పర్లేదు", tr: "parledu" },
    { en: "Wow / great", te: "భలే", tr: "bhale" },
    { en: "Oh no!", te: "అయ్యో", tr: "ayyo" },
    { en: "Oh my! (surprise)", te: "అమ్మో", tr: "ammo" },
  ]},
];
