/* Kannada curriculum — mirrors the Telugu structure (16 weeks, same themes)
   so all languages in the app feel consistent. Add cards to any week's
   `cards` array to expand — nothing else needs to change. */

const WEEKS_KN = [
  { month: 1, week: 1, theme: "Greetings & Politeness", cards: [
    { en: "Hello / Greetings", te: "ನಮಸ್ಕಾರ", tr: "namaskara" },
    { en: "How are you? (formal)", te: "ನೀವು ಹೇಗಿದ್ದೀರಿ?", tr: "neevu hegiddeeri?" },
    { en: "I am fine", te: "ನಾನು ಚೆನ್ನಾಗಿದ್ದೇನೆ", tr: "naanu chennaagiddene" },
    { en: "Thank you", te: "ಧನ್ಯವಾದಗಳು", tr: "dhanyavaadagalu" },
    { en: "Please", te: "ದಯವಿಟ್ಟು", tr: "dayavittu" },
    { en: "Sorry / Excuse me", te: "ಕ್ಷಮಿಸಿ", tr: "kshamisi" },
    { en: "Yes", te: "ಹೌದು", tr: "haudu" },
    { en: "No", te: "ಇಲ್ಲ", tr: "illa" },
    { en: "What is your name?", te: "ನಿಮ್ಮ ಹೆಸರೇನು?", tr: "nimma hesarenu?" },
    { en: "My name is ___", te: "ನನ್ನ ಹೆಸರು ___", tr: "nanna hesaru ___" },
    { en: "Good morning", te: "ಶುಭೋದಯ", tr: "shubhodaya" },
    { en: "Goodbye (casual)", te: "ಹೋಗಿ ಬರ್ತೀನಿ", tr: "hogi bartini", note: "Literally \"I'll go and come\" — the everyday casual way to say bye." },
  ]},
  { month: 1, week: 2, theme: "Pronouns & Basics", cards: [
    { en: "I", te: "ನಾನು", tr: "naanu" },
    { en: "You (respectful)", te: "ನೀವು", tr: "neevu", note: "Use with elders, strangers, colleagues." },
    { en: "You (casual)", te: "ನೀನು", tr: "neenu", note: "Only for close friends, kids, or people younger than you." },
    { en: "He", te: "ಅವನು", tr: "avanu" },
    { en: "She", te: "ಅವಳು", tr: "avalu" },
    { en: "We", te: "ನಾವು", tr: "naavu" },
    { en: "They", te: "ಅವರು", tr: "avaru" },
    { en: "This", te: "ಇದು", tr: "idu" },
    { en: "That", te: "ಅದು", tr: "adu" },
    { en: "Where", te: "ಎಲ್ಲಿ", tr: "elli" },
    { en: "What is this?", te: "ಇದು ಏನು?", tr: "idu enu?" },
    { en: "I am an engineer", te: "ನಾನು ಇಂಜಿನಿಯರ್", tr: "naanu engineer", note: "Kannada often drops \"am\" in identity statements — this is natural as-is." },
  ]},
  { month: 1, week: 3, theme: "Numbers & Time", cards: [
    { en: "One", te: "ಒಂದು", tr: "ondu" },
    { en: "Two", te: "ಎರಡು", tr: "eradu" },
    { en: "Three", te: "ಮೂರು", tr: "mooru" },
    { en: "Four", te: "ನಾಲ್ಕು", tr: "naalku" },
    { en: "Five", te: "ಐದು", tr: "aidu" },
    { en: "Six", te: "ಆರು", tr: "aaru" },
    { en: "Seven", te: "ಏಳು", tr: "elu" },
    { en: "Eight", te: "ಎಂಟು", tr: "entu" },
    { en: "Nine", te: "ಒಂಬತ್ತು", tr: "ombattu" },
    { en: "Ten", te: "ಹತ್ತು", tr: "hattu" },
    { en: "Today", te: "ಇವತ್ತು", tr: "ivattu" },
    { en: "Tomorrow", te: "ನಾಳೆ", tr: "naale" },
    { en: "Yesterday", te: "ನಿನ್ನೆ", tr: "ninne" },
    { en: "What's the time?", te: "ಸಮಯ ಎಷ್ಟು?", tr: "samaya eshtu?" },
  ]},
  { month: 1, week: 4, theme: "Family & People", cards: [
    { en: "Mother", te: "ಅಮ್ಮ", tr: "amma" },
    { en: "Father", te: "ಅಪ್ಪ", tr: "appa" },
    { en: "Elder brother", te: "ಅಣ್ಣ", tr: "anna" },
    { en: "Elder sister", te: "ಅಕ್ಕ", tr: "akka" },
    { en: "Friend (male)", te: "ಸ್ನೇಹಿತ", tr: "snehita" },
    { en: "Friend (female)", te: "ಸ್ನೇಹಿತೆ", tr: "snehite" },
    { en: "Children", te: "ಮಕ್ಕಳು", tr: "makkalu" },
    { en: "This is my friend", te: "ಇವನು ನನ್ನ ಸ್ನೇಹಿತ", tr: "ivanu nanna snehita", note: "\"ivanu\" (this person) is used for people instead of \"idu\"." },
  ]},
  { month: 2, week: 5, theme: "Everyday Verbs", cards: [
    { en: "I want tea", te: "ನನಗೆ ಟೀ ಬೇಕು", tr: "nanage tea beku", note: "Pattern: nanage ___ beku = \"I want ___\"" },
    { en: "I like it", te: "ನನಗೆ ಇಷ್ಟ", tr: "nanage ishta" },
    { en: "I don't like it", te: "ನನಗೆ ಇಷ್ಟ ಇಲ್ಲ", tr: "nanage ishta illa" },
    { en: "I understand", te: "ನನಗೆ ಅರ್ಥ ಆಯ್ತು", tr: "nanage artha aaytu" },
    { en: "I don't understand", te: "ನನಗೆ ಅರ್ಥ ಆಗಲಿಲ್ಲ", tr: "nanage artha aagalilla" },
    { en: "I know", te: "ನನಗೆ ಗೊತ್ತು", tr: "nanage gottu" },
    { en: "I don't know", te: "ನನಗೆ ಗೊತ್ತಿಲ್ಲ", tr: "nanage gottilla" },
    { en: "I am going", te: "ನಾನು ಹೋಗ್ತಿದ್ದೀನಿ", tr: "naanu hogtiddeeni" },
    { en: "I am coming", te: "ನಾನು ಬರ್ತಿದ್ದೀನಿ", tr: "naanu bartiddeeni" },
    { en: "I am eating", te: "ನಾನು ಊಟ ಮಾಡ್ತಿದ್ದೀನಿ", tr: "naanu oota maadtiddeeni" },
    { en: "Give me water", te: "ನನಗೆ ನೀರು ಕೊಡಿ", tr: "nanage neeru kodi" },
    { en: "Help me", te: "ನನಗೆ ಸಹಾಯ ಮಾಡಿ", tr: "nanage sahaaya maadi" },
  ]},
  { month: 2, week: 6, theme: "Asking Questions", cards: [
    { en: "What", te: "ಏನು", tr: "enu" },
    { en: "Who", te: "ಯಾರು", tr: "yaaru" },
    { en: "When", te: "ಯಾವಾಗ", tr: "yaavaaga" },
    { en: "Why", te: "ಯಾಕೆ", tr: "yaake" },
    { en: "How", te: "ಹೇಗೆ", tr: "hege" },
    { en: "How much / many", te: "ಎಷ್ಟು", tr: "eshtu" },
    { en: "Which", te: "ಯಾವುದು", tr: "yaavudu" },
    { en: "Can I get water?", te: "ನನಗೆ ನೀರು ಸಿಗುತ್ತಾ?", tr: "nanage neeru siguttaa?" },
    { en: "How much is this?", te: "ಇದು ಎಷ್ಟು?", tr: "idu eshtu?" },
    { en: "Is it available?", te: "ಇದೆಯಾ?", tr: "ideyaa?" },
  ]},
  { month: 2, week: 7, theme: "Food & Dining", cards: [
    { en: "Water", te: "ನೀರು", tr: "neeru" },
    { en: "Rice / food", te: "ಅನ್ನ", tr: "anna" },
    { en: "Meal", te: "ಊಟ", tr: "oota" },
    { en: "Tasty / good", te: "ಚೆನ್ನಾಗಿದೆ", tr: "chennaagide" },
    { en: "Spicy", te: "ಖಾರ", tr: "khaara" },
    { en: "Sweet", te: "ಸಿಹಿ", tr: "sihi" },
    { en: "I am hungry", te: "ನನಗೆ ಹಸಿವಾಗಿದೆ", tr: "nanage hasivaagide" },
    { en: "I am thirsty", te: "ನನಗೆ ಬಾಯಾರಿಕೆ ಆಗಿದೆ", tr: "nanage baayaarike aagide" },
    { en: "Coffee please", te: "ಕಾಫಿ ಕೊಡಿ", tr: "coffee kodi" },
    { en: "Do you have tea?", te: "ನಿಮ್ಮ ಹತ್ರ ಟೀ ಇದೆಯಾ?", tr: "nimma hatra tea ideyaa?" },
    { en: "Bill please", te: "ಬಿಲ್ ಕೊಡಿ", tr: "bill kodi" },
  ]},
  { month: 2, week: 8, theme: "Shopping & Directions", cards: [
    { en: "Shop", te: "ಅಂಗಡಿ", tr: "angadi" },
    { en: "Money", te: "ದುಡ್ಡು", tr: "duddu" },
    { en: "Expensive", te: "ದುಬಾರಿ", tr: "dubaari" },
    { en: "Cheap", te: "ಅಗ್ಗ", tr: "agga" },
    { en: "Left", te: "ಎಡ", tr: "eda" },
    { en: "Right", te: "ಬಲ", tr: "bala" },
    { en: "Straight", te: "ನೇರ", tr: "nera" },
    { en: "Near", te: "ಹತ್ತಿರ", tr: "hattira" },
    { en: "Far", te: "ದೂರ", tr: "doora" },
    { en: "Where is the bathroom?", te: "ಬಾತ್ರೂಮ್ ಎಲ್ಲಿದೆ?", tr: "bathroom ellide?" },
    { en: "Stop here", te: "ಇಲ್ಲಿ ನಿಲ್ಲಿಸಿ", tr: "illi nillisi" },
  ]},
  { month: 3, week: 9, theme: "Talking About the Past", cards: [
    { en: "I went", te: "ನಾನು ಹೋದೆ", tr: "naanu hode" },
    { en: "I came", te: "ನಾನು ಬಂದೆ", tr: "naanu bande" },
    { en: "I ate", te: "ನಾನು ಊಟ ಮಾಡಿದೆ", tr: "naanu oota maadide" },
    { en: "I did (it)", te: "ನಾನು ಮಾಡಿದೆ", tr: "naanu maadide" },
    { en: "I saw", te: "ನಾನು ನೋಡಿದೆ", tr: "naanu nodide" },
    { en: "I said", te: "ನಾನು ಹೇಳಿದೆ", tr: "naanu helide" },
    { en: "Did you eat?", te: "ನೀವು ಊಟ ಮಾಡಿದ್ರಾ?", tr: "neevu oota maadidraa?" },
    { en: "I finished it", te: "ನಾನು ಮುಗಿಸಿದೆ", tr: "naanu mugiside" },
  ]},
  { month: 3, week: 10, theme: "Talking About the Future", cards: [
    { en: "I will go", te: "ನಾನು ಹೋಗ್ತೀನಿ", tr: "naanu hogteeni" },
    { en: "I will come", te: "ನಾನು ಬರ್ತೀನಿ", tr: "naanu barteeni" },
    { en: "I will do it", te: "ನಾನು ಮಾಡ್ತೀನಿ", tr: "naanu maadteeni" },
    { en: "I will call you", te: "ನಾನು ನಿಮಗೆ ಕಾಲ್ ಮಾಡ್ತೀನಿ", tr: "naanu nimage call maadteeni" },
    { en: "Will you come?", te: "ನೀವು ಬರ್ತೀರಾ?", tr: "neevu barteeraa?" },
    { en: "See you tomorrow", te: "ನಾಳೆ ಸಿಗೋಣ", tr: "naale sigona" },
  ]},
  { month: 3, week: 11, theme: "Feelings & States", cards: [
    { en: "Happiness", te: "ಸಂತೋಷ", tr: "santosha" },
    { en: "Sadness", te: "ದುಃಖ", tr: "dukkha" },
    { en: "I am tired", te: "ನನಗೆ ಸುಸ್ತಾಗಿದೆ", tr: "nanage sustaagide" },
    { en: "I am angry", te: "ನನಗೆ ಕೋಪ ಬಂದಿದೆ", tr: "nanage kopa bandide" },
    { en: "I am not feeling well", te: "ನನಗೆ ಮೈ ಹುಷಾರಿಲ್ಲ", tr: "nanage mai hushaarilla" },
    { en: "I am scared", te: "ನನಗೆ ಭಯ ಆಗ್ತಿದೆ", tr: "nanage bhaya aagtide" },
    { en: "I love you", te: "ನಾನು ನಿನ್ನ ಪ್ರೀತಿಸ್ತೀನಿ", tr: "naanu ninna preetisteeni" },
    { en: "I'm so happy", te: "ನನಗೆ ತುಂಬಾ ಸಂತೋಷ ಆಗ್ತಿದೆ", tr: "nanage tumba santosha aagtide" },
  ]},
  { month: 3, week: 12, theme: "Connecting Words", cards: [
    { en: "And / also", te: "ಮತ್ತು", tr: "mattu" },
    { en: "But", te: "ಆದರೆ", tr: "aadare" },
    { en: "Because", te: "ಯಾಕಂದ್ರೆ", tr: "yaakandre" },
    { en: "If", te: "ಒಂದು ವೇಳೆ", tr: "ondu vele" },
    { en: "Also / too", te: "ಕೂಡ", tr: "kooda" },
    { en: "Okay / alright", te: "ಸರಿ", tr: "sari" },
    { en: "Really?", te: "ನಿಜವಾಗ್ಲೂ?", tr: "nijavaaglu?" },
    { en: "Wait", te: "ತಡೀರಿ", tr: "tadeeri" },
    { en: "Come here", te: "ಇಲ್ಲಿ ಬನ್ನಿ", tr: "illi banni" },
    { en: "Listen", te: "ಕೇಳಿ", tr: "keli" },
  ]},
  { month: 4, week: 13, theme: "At a Shop", cards: [
    { en: "Do you have this?", te: "ನಿಮ್ಮ ಹತ್ರ ಇದೆಯಾ?", tr: "nimma hatra ideyaa?" },
    { en: "I need an auto", te: "ನನಗೆ ಆಟೋ ಬೇಕು", tr: "nanage auto beku" },
    { en: "Please reduce the price", te: "ರೇಟ್ ಕಡಿಮೆ ಮಾಡಿ", tr: "rate kadime maadi" },
    { en: "I'll take this", te: "ಇದನ್ನ ತಗೋತೀನಿ", tr: "idanna tagoteeni" },
    { en: "No need", te: "ಬೇಡ", tr: "beda", note: "Very common word — the polite way to decline anything." },
    { en: "Enough / that's it", te: "ಸಾಕು", tr: "saaku" },
  ]},
  { month: 4, week: 14, theme: "Meeting People", cards: [
    { en: "Where are you from?", te: "ನೀವು ಎಲ್ಲಿಂದ?", tr: "neevu ellinda?" },
    { en: "I am from Bengaluru", te: "ನಾನು ಬೆಂಗಳೂರಿಂದ", tr: "naanu bengalurinda" },
    { en: "What do you do?", te: "ನೀವು ಏನು ಮಾಡ್ತೀರಾ?", tr: "neevu enu maadteeraa?" },
    { en: "I work at Bosch", te: "ನಾನು ಬಾಷ್ ಕಂಪನಿಯಲ್ಲಿ ಕೆಲಸ ಮಾಡ್ತೀನಿ", tr: "naanu Bosch company-yalli kelasa maadteeni" },
    { en: "Nice to meet you", te: "ನಿಮ್ಮನ್ನ ಭೇಟಿ ಆಗಿದ್ದು ಖುಷಿ ಆಯ್ತು", tr: "nimmanna bheti aagiddu khushi aaytu" },
    { en: "How old are you?", te: "ನಿಮ್ಮ ವಯಸ್ಸು ಎಷ್ಟು?", tr: "nimma vayassu eshtu?" },
  ]},
  { month: 4, week: 15, theme: "Travel & Transport", cards: [
    { en: "Bus stop", te: "ಬಸ್ ಸ್ಟಾಪ್", tr: "bus stop" },
    { en: "Auto rickshaw", te: "ಆಟೋ", tr: "auto" },
    { en: "Turn left", te: "ಎಡಕ್ಕೆ ತಿರುಗಿ", tr: "edakke tirugi" },
    { en: "Turn right", te: "ಬಲಕ್ಕೆ ತಿರುಗಿ", tr: "balakke tirugi" },
    { en: "How far is it?", te: "ಎಷ್ಟು ದೂರ?", tr: "eshtu doora?" },
    { en: "Take me to the airport", te: "ನನ್ನ ಏರ್‌ಪೋರ್ಟ್‌ಗೆ ಕರ್ಕೊಂಡು ಹೋಗಿ", tr: "nanna airport-ge karkondu hogi" },
  ]},
  { month: 4, week: 16, theme: "Everyday Fillers & Review", cards: [
    { en: "Sure / okay then", te: "ಆಯ್ತು", tr: "aaytu" },
    { en: "Anything else?", te: "ಇನ್ನೇನಾದ್ರೂ ಬೇಕಾ?", tr: "innenaadru bekaa?" },
    { en: "No problem / it's okay", te: "ಪರವಾಗಿಲ್ಲ", tr: "paravaagilla" },
    { en: "Wow / great", te: "ಭಲೇ", tr: "bhale" },
    { en: "Oh no!", te: "ಅಯ್ಯೋ", tr: "ayyo" },
    { en: "Oh my! (surprise)", te: "ಅಬ್ಬಬ್ಬಾ", tr: "abbabba" },
  ]},
];
