/* Japanese curriculum — mirrors the other languages' structure (16 weeks,
   same themes). "te" holds natural Japanese script (kanji + hiragana);
   "tr" holds romaji. Uses polite -masu/desu form throughout, the standard
   safe register for beginners talking with people they don't know well. */

const WEEKS_JA = [
  { month: 1, week: 1, theme: "Greetings & Politeness", cards: [
    { en: "Hello", te: "こんにちは", tr: "konnichiwa" },
    { en: "How are you? (formal)", te: "お元気ですか？", tr: "o-genki desu ka?" },
    { en: "I am fine", te: "元気です", tr: "genki desu" },
    { en: "Thank you", te: "ありがとうございます", tr: "arigatou gozaimasu" },
    { en: "Please", te: "お願いします", tr: "onegaishimasu" },
    { en: "Sorry / Excuse me", te: "すみません", tr: "sumimasen" },
    { en: "Yes", te: "はい", tr: "hai" },
    { en: "No", te: "いいえ", tr: "iie" },
    { en: "What is your name?", te: "お名前は何ですか？", tr: "o-namae wa nan desu ka?" },
    { en: "My name is ___", te: "私の名前は___です", tr: "watashi no namae wa ___ desu" },
    { en: "Good morning", te: "おはようございます", tr: "ohayou gozaimasu" },
    { en: "Goodbye (casual)", te: "じゃあね", tr: "jaa ne", note: "Casual, friendly goodbye — \"さようなら\" (sayounara) sounds more formal or final." },
  ]},
  { month: 1, week: 2, theme: "Pronouns & Basics", cards: [
    { en: "I", te: "私", tr: "watashi" },
    { en: "You (formal / neutral)", te: "あなた", tr: "anata", note: "Used sparingly — it's usually more natural to say the person's name + さん (-san)." },
    { en: "You (casual)", te: "君", tr: "kimi", note: "Casual, often used by men to close friends or juniors. Using the person's name + さん is safer." },
    { en: "He", te: "彼", tr: "kare" },
    { en: "She", te: "彼女", tr: "kanojo" },
    { en: "We", te: "私たち", tr: "watashi-tachi" },
    { en: "They", te: "彼ら", tr: "karera" },
    { en: "This", te: "これ", tr: "kore" },
    { en: "That", te: "それ", tr: "sore" },
    { en: "Where", te: "どこ", tr: "doko" },
    { en: "What is this?", te: "これは何ですか？", tr: "kore wa nan desu ka?" },
    { en: "I am an engineer", te: "私はエンジニアです", tr: "watashi wa enjinia desu" },
  ]},
  { month: 1, week: 3, theme: "Numbers & Time", cards: [
    { en: "One", te: "一", tr: "ichi" },
    { en: "Two", te: "二", tr: "ni" },
    { en: "Three", te: "三", tr: "san" },
    { en: "Four", te: "四", tr: "yon" },
    { en: "Five", te: "五", tr: "go" },
    { en: "Six", te: "六", tr: "roku" },
    { en: "Seven", te: "七", tr: "nana" },
    { en: "Eight", te: "八", tr: "hachi" },
    { en: "Nine", te: "九", tr: "kyuu" },
    { en: "Ten", te: "十", tr: "juu" },
    { en: "Today", te: "今日", tr: "kyou" },
    { en: "Tomorrow", te: "明日", tr: "ashita" },
    { en: "Yesterday", te: "昨日", tr: "kinou" },
    { en: "What's the time?", te: "今何時ですか？", tr: "ima nanji desu ka?" },
  ]},
  { month: 1, week: 4, theme: "Family & People", cards: [
    { en: "Mother", te: "母", tr: "haha", note: "Use \"haha\" for your own mother when talking to others; お母さん (okaasan) for someone else's mother." },
    { en: "Father", te: "父", tr: "chichi", note: "Use \"chichi\" for your own father; お父さん (otousan) for someone else's father." },
    { en: "Elder brother", te: "兄", tr: "ani" },
    { en: "Elder sister", te: "姉", tr: "ane" },
    { en: "Friend", te: "友達", tr: "tomodachi", note: "Gender-neutral — unlike Telugu/Kannada, Japanese doesn't mark the friend's gender." },
    { en: "Family", te: "家族", tr: "kazoku" },
    { en: "Children", te: "子供たち", tr: "kodomo-tachi" },
    { en: "This is my friend", te: "こちらは友達です", tr: "kochira wa tomodachi desu" },
  ]},
  { month: 2, week: 5, theme: "Everyday Verbs", cards: [
    { en: "I want tea", te: "お茶が欲しいです", tr: "ocha ga hoshii desu", note: "Pattern: [thing] が欲しいです = \"I want [thing]\"" },
    { en: "I like it", te: "好きです", tr: "suki desu" },
    { en: "I don't like it", te: "好きじゃないです", tr: "suki janai desu" },
    { en: "I understand", te: "わかりました", tr: "wakarimashita" },
    { en: "I don't understand", te: "わかりません", tr: "wakarimasen" },
    { en: "I know", te: "知っています", tr: "shitte imasu" },
    { en: "I don't know", te: "知りません", tr: "shirimasen" },
    { en: "I am going", te: "行きます", tr: "ikimasu" },
    { en: "I am coming", te: "来ます", tr: "kimasu" },
    { en: "I am eating", te: "食べます", tr: "tabemasu" },
    { en: "Give me water", te: "水をください", tr: "mizu wo kudasai" },
    { en: "Help me", te: "助けてください", tr: "tasukete kudasai" },
  ]},
  { month: 2, week: 6, theme: "Asking Questions", cards: [
    { en: "What", te: "何", tr: "nani" },
    { en: "Who", te: "誰", tr: "dare" },
    { en: "When", te: "いつ", tr: "itsu" },
    { en: "Why", te: "どうして", tr: "doushite" },
    { en: "How", te: "どうやって", tr: "dou yatte" },
    { en: "How much / many", te: "いくつ", tr: "ikutsu" },
    { en: "Which", te: "どれ", tr: "dore" },
    { en: "Can I get water?", te: "水をもらえますか？", tr: "mizu wo moraemasu ka?" },
    { en: "How much is this?", te: "これはいくらですか？", tr: "kore wa ikura desu ka?" },
    { en: "Is it available?", te: "ありますか？", tr: "arimasu ka?" },
  ]},
  { month: 2, week: 7, theme: "Food & Dining", cards: [
    { en: "Water", te: "水", tr: "mizu" },
    { en: "Rice / food", te: "ご飯", tr: "gohan" },
    { en: "Meal", te: "食事", tr: "shokuji" },
    { en: "Tasty / good", te: "おいしい", tr: "oishii" },
    { en: "Spicy", te: "辛い", tr: "karai" },
    { en: "Sweet", te: "甘い", tr: "amai" },
    { en: "I am hungry", te: "お腹が空きました", tr: "onaka ga sukimashita" },
    { en: "I am thirsty", te: "喉が渇きました", tr: "nodo ga kawakimashita" },
    { en: "Coffee please", te: "コーヒーをください", tr: "koohii wo kudasai" },
    { en: "Do you have tea?", te: "お茶はありますか？", tr: "ocha wa arimasu ka?" },
    { en: "Bill please", te: "お会計をお願いします", tr: "okaikei wo onegaishimasu" },
  ]},
  { month: 2, week: 8, theme: "Shopping & Directions", cards: [
    { en: "Shop", te: "店", tr: "mise" },
    { en: "Money", te: "お金", tr: "okane" },
    { en: "Expensive", te: "高い", tr: "takai" },
    { en: "Cheap", te: "安い", tr: "yasui" },
    { en: "Left", te: "左", tr: "hidari" },
    { en: "Right", te: "右", tr: "migi" },
    { en: "Straight", te: "まっすぐ", tr: "massugu" },
    { en: "Near", te: "近い", tr: "chikai" },
    { en: "Far", te: "遠い", tr: "tooi" },
    { en: "Where is the bathroom?", te: "トイレはどこですか？", tr: "toire wa doko desu ka?" },
    { en: "Stop here", te: "ここで止めてください", tr: "koko de tomete kudasai" },
  ]},
  { month: 3, week: 9, theme: "Talking About the Past", cards: [
    { en: "I went", te: "行きました", tr: "ikimashita" },
    { en: "I came", te: "来ました", tr: "kimashita" },
    { en: "I ate", te: "食べました", tr: "tabemashita" },
    { en: "I did (it)", te: "しました", tr: "shimashita" },
    { en: "I saw", te: "見ました", tr: "mimashita" },
    { en: "I said", te: "言いました", tr: "iimashita" },
    { en: "Did you eat?", te: "食べましたか？", tr: "tabemashita ka?" },
    { en: "I finished it", te: "終わりました", tr: "owarimashita" },
  ]},
  { month: 3, week: 10, theme: "Talking About the Future", cards: [
    { en: "I will go", te: "行きます", tr: "ikimasu", note: "Japanese uses the same form for present and future — context/time words show which is meant." },
    { en: "I will come", te: "来ます", tr: "kimasu" },
    { en: "I will do it", te: "します", tr: "shimasu" },
    { en: "I will call you", te: "電話します", tr: "denwa shimasu" },
    { en: "Will you come?", te: "来ますか？", tr: "kimasu ka?" },
    { en: "See you tomorrow", te: "また明日", tr: "mata ashita" },
  ]},
  { month: 3, week: 11, theme: "Feelings & States", cards: [
    { en: "Happiness", te: "幸せ", tr: "shiawase" },
    { en: "Sadness", te: "悲しみ", tr: "kanashimi" },
    { en: "I am tired", te: "疲れました", tr: "tsukaremashita" },
    { en: "I am angry", te: "怒っています", tr: "okotte imasu" },
    { en: "I am not feeling well", te: "気分が悪いです", tr: "kibun ga warui desu" },
    { en: "I am scared", te: "怖いです", tr: "kowai desu" },
    { en: "I love you", te: "愛してます", tr: "aishitemasu" },
    { en: "I'm so happy", te: "とても嬉しいです", tr: "totemo ureshii desu" },
  ]},
  { month: 3, week: 12, theme: "Connecting Words", cards: [
    { en: "And / also", te: "そして", tr: "soshite" },
    { en: "But", te: "でも", tr: "demo" },
    { en: "Because", te: "から", tr: "kara" },
    { en: "If", te: "もし", tr: "moshi" },
    { en: "Also / too", te: "も", tr: "mo" },
    { en: "Okay / alright", te: "いいですよ", tr: "ii desu yo" },
    { en: "Really?", te: "本当ですか？", tr: "hontou desu ka?" },
    { en: "Wait", te: "待ってください", tr: "matte kudasai" },
    { en: "Come here", te: "こっちに来てください", tr: "kocchi ni kite kudasai" },
    { en: "Listen", te: "聞いてください", tr: "kiite kudasai" },
  ]},
  { month: 4, week: 13, theme: "At a Shop", cards: [
    { en: "Do you have this?", te: "これはありますか？", tr: "kore wa arimasu ka?" },
    { en: "I need a taxi", te: "タクシーが必要です", tr: "takushii ga hitsuyou desu" },
    { en: "Please reduce the price", te: "安くしてください", tr: "yasuku shite kudasai" },
    { en: "I'll take this", te: "これをください", tr: "kore wo kudasai" },
    { en: "No need", te: "大丈夫です", tr: "daijoubu desu", note: "Literally \"it's fine\" — the natural polite way to decline something offered." },
    { en: "Enough / that's it", te: "もう十分です", tr: "mou juubun desu" },
  ]},
  { month: 4, week: 14, theme: "Meeting People", cards: [
    { en: "Where are you from?", te: "どこから来ましたか？", tr: "doko kara kimashita ka?" },
    { en: "I am from Bengaluru", te: "ベンガルールから来ました", tr: "Bengaluru kara kimashita" },
    { en: "What do you do?", te: "お仕事は何ですか？", tr: "oshigoto wa nan desu ka?" },
    { en: "I work at Bosch", te: "ボッシュで働いています", tr: "Bosshu de hataraite imasu" },
    { en: "Nice to meet you", te: "はじめまして", tr: "hajimemashite" },
    { en: "How old are you?", te: "おいくつですか？", tr: "oikutsu desu ka?" },
  ]},
  { month: 4, week: 15, theme: "Travel & Transport", cards: [
    { en: "Bus stop", te: "バス停", tr: "basutei" },
    { en: "Taxi", te: "タクシー", tr: "takushii" },
    { en: "Turn left", te: "左に曲がってください", tr: "hidari ni magatte kudasai" },
    { en: "Turn right", te: "右に曲がってください", tr: "migi ni magatte kudasai" },
    { en: "How far is it?", te: "どのくらい遠いですか？", tr: "dono kurai tooi desu ka?" },
    { en: "Take me to the airport", te: "空港まで連れて行ってください", tr: "kuukou made tsurete itte kudasai" },
  ]},
  { month: 4, week: 16, theme: "Everyday Fillers & Review", cards: [
    { en: "Sure / okay then", te: "じゃあ、いいですよ", tr: "jaa, ii desu yo" },
    { en: "Anything else?", te: "他に何か？", tr: "hoka ni nanika?" },
    { en: "No problem / it's okay", te: "大丈夫です", tr: "daijoubu desu" },
    { en: "Wow / great", te: "すごい！", tr: "sugoi!" },
    { en: "Oh no!", te: "あ、大変！", tr: "a, taihen!" },
    { en: "Oh my! (surprise)", te: "えっ！", tr: "e!" },
  ]},
];
