/* German curriculum — mirrors the Telugu/Kannada structure (16 weeks, same
   themes). "te" holds correct German spelling; "tr" holds a simplified
   English-reader-friendly pronunciation guide (German is Latin-script, so
   this is a pronunciation aid rather than a transliteration). */

const WEEKS_DE = [
  { month: 1, week: 1, theme: "Greetings & Politeness", cards: [
    { en: "Hello", te: "Hallo", tr: "HAH-loh" },
    { en: "How are you? (formal)", te: "Wie geht es Ihnen?", tr: "vee gayt es EE-nen" },
    { en: "I am fine", te: "Mir geht es gut", tr: "meer gayt es goot" },
    { en: "Thank you", te: "Danke", tr: "DAHN-kuh" },
    { en: "Please", te: "Bitte", tr: "BIT-uh" },
    { en: "Sorry / Excuse me", te: "Entschuldigung", tr: "ent-SHUL-di-gung" },
    { en: "Yes", te: "Ja", tr: "yah" },
    { en: "No", te: "Nein", tr: "nine" },
    { en: "What is your name?", te: "Wie heißen Sie?", tr: "vee HY-sen zee" },
    { en: "My name is ___", te: "Ich heiße ___", tr: "ikh HY-suh ___" },
    { en: "Good morning", te: "Guten Morgen", tr: "GOO-ten MOR-gen" },
    { en: "Goodbye (casual)", te: "Tschüss", tr: "chuess", note: "The everyday casual way to say bye — \"Auf Wiedersehen\" is more formal." },
  ]},
  { month: 1, week: 2, theme: "Pronouns & Basics", cards: [
    { en: "I", te: "ich", tr: "ikh" },
    { en: "You (respectful)", te: "Sie", tr: "zee", note: "Capital \"Sie\" — use with strangers, elders, in professional settings." },
    { en: "You (casual)", te: "du", tr: "doo", note: "Only for friends, family, children." },
    { en: "He", te: "er", tr: "air" },
    { en: "She", te: "sie", tr: "zee", note: "Same spelling as formal \"you\" — verb form and context tell them apart." },
    { en: "We", te: "wir", tr: "veer" },
    { en: "They", te: "sie", tr: "zee", note: "German reuses \"sie\" for she/they/formal-you — context and capitalization disambiguate." },
    { en: "This", te: "das hier", tr: "dahs heer" },
    { en: "That", te: "das da", tr: "dahs dah" },
    { en: "Where", te: "wo", tr: "voh" },
    { en: "What is this?", te: "Was ist das?", tr: "vahs ist dahs" },
    { en: "I am an engineer", te: "Ich bin Ingenieur", tr: "ikh bin in-zhen-YUR" },
  ]},
  { month: 1, week: 3, theme: "Numbers & Time", cards: [
    { en: "One", te: "eins", tr: "ines" },
    { en: "Two", te: "zwei", tr: "tsvy" },
    { en: "Three", te: "drei", tr: "dry" },
    { en: "Four", te: "vier", tr: "feer" },
    { en: "Five", te: "fünf", tr: "fewnf" },
    { en: "Six", te: "sechs", tr: "zex" },
    { en: "Seven", te: "sieben", tr: "ZEE-ben" },
    { en: "Eight", te: "acht", tr: "ahkht" },
    { en: "Nine", te: "neun", tr: "noyn" },
    { en: "Ten", te: "zehn", tr: "tsayn" },
    { en: "Today", te: "heute", tr: "HOY-tuh" },
    { en: "Tomorrow", te: "morgen", tr: "MOR-gen" },
    { en: "Yesterday", te: "gestern", tr: "GES-tern" },
    { en: "What's the time?", te: "Wie spät ist es?", tr: "vee shpayt ist es" },
  ]},
  { month: 1, week: 4, theme: "Family & People", cards: [
    { en: "Mother", te: "Mutter", tr: "MUT-er" },
    { en: "Father", te: "Vater", tr: "FAH-ter" },
    { en: "Elder brother", te: "großer Bruder", tr: "GROH-ser BROO-der" },
    { en: "Elder sister", te: "große Schwester", tr: "GROH-suh SHVES-ter" },
    { en: "Friend (male)", te: "Freund", tr: "froynt" },
    { en: "Friend (female)", te: "Freundin", tr: "FROYN-din" },
    { en: "Children", te: "Kinder", tr: "KIN-der" },
    { en: "This is my friend", te: "Das ist mein Freund", tr: "dahs ist mine froynt" },
  ]},
  { month: 2, week: 5, theme: "Everyday Verbs", cards: [
    { en: "I want tea", te: "Ich möchte Tee", tr: "ikh MERKH-tuh tay", note: "Pattern: Ich möchte ___ = \"I would like ___\"" },
    { en: "I like it", te: "Das gefällt mir", tr: "dahs guh-FELT meer" },
    { en: "I don't like it", te: "Das gefällt mir nicht", tr: "dahs guh-FELT meer nikht" },
    { en: "I understand", te: "Ich verstehe", tr: "ikh fer-SHTAY-uh" },
    { en: "I don't understand", te: "Ich verstehe nicht", tr: "ikh fer-SHTAY-uh nikht" },
    { en: "I know", te: "Ich weiß", tr: "ikh vice" },
    { en: "I don't know", te: "Ich weiß nicht", tr: "ikh vice nikht" },
    { en: "I am going", te: "Ich gehe", tr: "ikh GAY-uh" },
    { en: "I am coming", te: "Ich komme", tr: "ikh KOM-uh" },
    { en: "I am eating", te: "Ich esse", tr: "ikh ES-uh" },
    { en: "Give me water", te: "Gib mir Wasser", tr: "geeb meer VAH-ser" },
    { en: "Help me", te: "Hilf mir", tr: "hilf meer" },
  ]},
  { month: 2, week: 6, theme: "Asking Questions", cards: [
    { en: "What", te: "was", tr: "vahs" },
    { en: "Who", te: "wer", tr: "vair" },
    { en: "When", te: "wann", tr: "vahn" },
    { en: "Why", te: "warum", tr: "vah-ROOM" },
    { en: "How", te: "wie", tr: "vee" },
    { en: "How much / many", te: "wie viel", tr: "vee feel" },
    { en: "Which", te: "welche", tr: "VEL-khuh" },
    { en: "Can I get water?", te: "Kann ich Wasser bekommen?", tr: "kahn ikh VAH-ser buh-KOM-en" },
    { en: "How much is this?", te: "Wie viel kostet das?", tr: "vee feel KOS-tet dahs" },
    { en: "Is it available?", te: "Ist das verfügbar?", tr: "ist dahs fer-FEWG-bar" },
  ]},
  { month: 2, week: 7, theme: "Food & Dining", cards: [
    { en: "Water", te: "Wasser", tr: "VAH-ser" },
    { en: "Rice", te: "Reis", tr: "rice" },
    { en: "Meal", te: "Mahlzeit", tr: "MAHL-tsyte" },
    { en: "Tasty / good", te: "lecker", tr: "LEK-er" },
    { en: "Spicy", te: "scharf", tr: "shahrf" },
    { en: "Sweet", te: "süß", tr: "zewss" },
    { en: "I am hungry", te: "Ich habe Hunger", tr: "ikh HAH-buh HOONG-er" },
    { en: "I am thirsty", te: "Ich habe Durst", tr: "ikh HAH-buh doorst" },
    { en: "Coffee please", te: "Kaffee, bitte", tr: "KAH-fay BIT-uh" },
    { en: "Do you have tea?", te: "Haben Sie Tee?", tr: "HAH-ben zee tay" },
    { en: "Bill please", te: "Die Rechnung, bitte", tr: "dee REKH-noong BIT-uh" },
  ]},
  { month: 2, week: 8, theme: "Shopping & Directions", cards: [
    { en: "Shop", te: "Geschäft", tr: "guh-SHEFT" },
    { en: "Money", te: "Geld", tr: "gelt" },
    { en: "Expensive", te: "teuer", tr: "TOY-er" },
    { en: "Cheap", te: "billig", tr: "BIL-ikh" },
    { en: "Left", te: "links", tr: "links" },
    { en: "Right", te: "rechts", tr: "rekhts" },
    { en: "Straight", te: "geradeaus", tr: "guh-RAH-duh-ows" },
    { en: "Near", te: "nah", tr: "nah" },
    { en: "Far", te: "weit", tr: "vite" },
    { en: "Where is the bathroom?", te: "Wo ist die Toilette?", tr: "voh ist dee twa-LET-uh" },
    { en: "Stop here", te: "Halten Sie hier", tr: "HAHL-ten zee heer" },
  ]},
  { month: 3, week: 9, theme: "Talking About the Past", cards: [
    { en: "I went", te: "Ich bin gegangen", tr: "ikh bin guh-GAHNG-en" },
    { en: "I came", te: "Ich bin gekommen", tr: "ikh bin guh-KOM-en" },
    { en: "I ate", te: "Ich habe gegessen", tr: "ikh HAH-buh guh-GES-en" },
    { en: "I did (it)", te: "Ich habe es gemacht", tr: "ikh HAH-buh es guh-MAHKHT" },
    { en: "I saw", te: "Ich habe gesehen", tr: "ikh HAH-buh guh-ZAY-en" },
    { en: "I said", te: "Ich habe gesagt", tr: "ikh HAH-buh guh-ZAHKT" },
    { en: "Did you eat?", te: "Haben Sie gegessen?", tr: "HAH-ben zee guh-GES-en" },
    { en: "I finished it", te: "Ich bin fertig damit", tr: "ikh bin FER-tikh dah-MIT" },
  ]},
  { month: 3, week: 10, theme: "Talking About the Future", cards: [
    { en: "I will go", te: "Ich werde gehen", tr: "ikh VER-duh GAY-en" },
    { en: "I will come", te: "Ich werde kommen", tr: "ikh VER-duh KOM-en" },
    { en: "I will do it", te: "Ich werde es tun", tr: "ikh VER-duh es toon" },
    { en: "I will call you", te: "Ich werde Sie anrufen", tr: "ikh VER-duh zee AHN-roo-fen" },
    { en: "Will you come?", te: "Werden Sie kommen?", tr: "VER-den zee KOM-en" },
    { en: "See you tomorrow", te: "Bis morgen", tr: "bis MOR-gen" },
  ]},
  { month: 3, week: 11, theme: "Feelings & States", cards: [
    { en: "Happiness", te: "Freude", tr: "FROY-duh" },
    { en: "Sadness", te: "Traurigkeit", tr: "TROW-rikh-kite" },
    { en: "I am tired", te: "Ich bin müde", tr: "ikh bin MEW-duh" },
    { en: "I am angry", te: "Ich bin wütend", tr: "ikh bin VEW-tent" },
    { en: "I am not feeling well", te: "Mir geht es nicht gut", tr: "meer gayt es nikht goot" },
    { en: "I am scared", te: "Ich habe Angst", tr: "ikh HAH-buh ahngst" },
    { en: "I love you", te: "Ich liebe dich", tr: "ikh LEE-buh dikh" },
    { en: "I'm so happy", te: "Ich bin so glücklich", tr: "ikh bin zoh GLEWK-likh" },
  ]},
  { month: 3, week: 12, theme: "Connecting Words", cards: [
    { en: "And", te: "und", tr: "oont" },
    { en: "But", te: "aber", tr: "AH-ber" },
    { en: "Because", te: "weil", tr: "vile" },
    { en: "If", te: "wenn", tr: "ven" },
    { en: "Also / too", te: "auch", tr: "owkh" },
    { en: "Okay / alright", te: "gut", tr: "goot" },
    { en: "Really?", te: "Wirklich?", tr: "VEERK-likh" },
    { en: "Wait", te: "Warten Sie", tr: "VAR-ten zee" },
    { en: "Come here", te: "Kommen Sie her", tr: "KOM-en zee hair" },
    { en: "Listen", te: "Hören Sie", tr: "HUR-en zee" },
  ]},
  { month: 4, week: 13, theme: "At a Shop", cards: [
    { en: "Do you have this?", te: "Haben Sie das?", tr: "HAH-ben zee dahs" },
    { en: "I need a taxi", te: "Ich brauche ein Taxi", tr: "ikh BROW-khuh ine TAHK-see" },
    { en: "Can you reduce the price?", te: "Können Sie den Preis senken?", tr: "KUR-nen zee dayn price ZENK-en" },
    { en: "I'll take this", te: "Ich nehme das", tr: "ikh NAY-muh dahs" },
    { en: "No need", te: "Nicht nötig", tr: "nikht NUR-tikh", note: "A polite way to decline something offered." },
    { en: "Enough / that's it", te: "Das reicht", tr: "dahs rykht" },
  ]},
  { month: 4, week: 14, theme: "Meeting People", cards: [
    { en: "Where are you from?", te: "Woher kommen Sie?", tr: "voh-HAIR KOM-en zee" },
    { en: "I am from Bengaluru", te: "Ich komme aus Bengaluru", tr: "ikh KOM-uh ows Ben-ga-loo-roo" },
    { en: "What do you do?", te: "Was machen Sie beruflich?", tr: "vahs MAHKH-en zee buh-ROOF-likh" },
    { en: "I work at Bosch", te: "Ich arbeite bei Bosch", tr: "ikh AHR-by-tuh by Bosch" },
    { en: "Nice to meet you", te: "Schön, Sie kennenzulernen", tr: "shurn zee KEN-en-tsoo-lair-nen" },
    { en: "How old are you?", te: "Wie alt sind Sie?", tr: "vee ahlt zint zee" },
  ]},
  { month: 4, week: 15, theme: "Travel & Transport", cards: [
    { en: "Bus stop", te: "Bushaltestelle", tr: "BOOS-hahl-tuh-shtel-uh" },
    { en: "Taxi", te: "Taxi", tr: "TAHK-see" },
    { en: "Turn left", te: "Biegen Sie links ab", tr: "BEE-gen zee links ahb" },
    { en: "Turn right", te: "Biegen Sie rechts ab", tr: "BEE-gen zee rekhts ahb" },
    { en: "How far is it?", te: "Wie weit ist es?", tr: "vee vite ist es" },
    { en: "Take me to the airport", te: "Bringen Sie mich zum Flughafen", tr: "BRING-en zee mikh tsoom FLOOG-hah-fen" },
  ]},
  { month: 4, week: 16, theme: "Everyday Fillers & Review", cards: [
    { en: "Sure / okay then", te: "Alles klar", tr: "AH-les klar" },
    { en: "Anything else?", te: "Sonst noch etwas?", tr: "zonst nokh ET-vahs" },
    { en: "No problem / it's okay", te: "Kein Problem", tr: "kine proh-BLAYM" },
    { en: "Wow / great", te: "Toll!", tr: "tol" },
    { en: "Oh no!", te: "Oh nein!", tr: "oh nine" },
    { en: "Oh my! (surprise)", te: "Ach du meine Güte!", tr: "ahkh doo MY-nuh GEW-tuh" },
  ]},
];
